[project]
name = "30122-project-asia-pacific-enthusiastic-coding-apec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipython>=8.32.0",
    "pandas>=2.2.3",
]
