NATION_DROPDOWN = "nation-dropdown"
SELECT_ALL_NATIONS_BUTTON = "select-all-nations-button"
YEAR_DROPDOWN = "year-dropdown"
MONTH_DROPDOWN = "month-dropdown"
SELECT_YEAR_BUTTON = "select-year-button"
SELECT_MONTH_BUTTON = "select-month-button"

BAR_CHART = "bar-chart"
TREE_MAP = "tree-map"
MAP = "map"
HHINDEX_CHART = "hhindex-chart"
