from get_trade_data import url_to_cache_key, get_data_census
import pandas as pd
import json
from pathlib import Path

COUNTRIES=['AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANDORRA', 'ANGOLA', 'ANGUILLA', 'ARGENTINA', 'ARMENIA', 'ARUBA', 
               'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUS', 'BELGIUM', 
               'BELIZE', 'BENIN', 'BERMUDA', 'BHUTAN', 'BOLIVIA', 'BOTSWANA', 'BRAZIL',  'BRUNEI', 
               'BULGARIA', 'BURKINA FASO', 'BURMA', 'BURUNDI', 'CABO VERDE', 'CAMBODIA', 'CAMEROON', 'CANADA', 'CAYMAN ISLANDS', 
               'CHAD', 'CHILE', 'CHINA', 'COLOMBIA','COMOROS',  'COSTA RICA', 'CROATIA', 
               'CUBA', 'CURACAO', 'CYPRUS', 'CZECH REPUBLIC', 'DENMARK', 'DJIBOUTI', 'DOMINICA', 'ECUADOR', 
               'EGYPT', 'EL SALVADOR', 'ESTONIA', 'ESWATINI', 'ETHIOPIA', 
               'FAROE ISLANDS', 'FINLAND', 'FRANCE',  'GABON', 
               'GAMBIA', 'GEORGIA', 'GERMANY', 'GHANA', 'GIBRALTAR', 'GREECE', 'GREENLAND', 'GRENADA', 'GUADELOUPE', 'GUATEMALA', 'GUINEA', 'GUINEA-BISSAU',
                'GUYANA', 'HAITI', 'HONDURAS', 'HONG KONG', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'IRELAND', 'ISRAEL', 'ITALY', 'JAMAICA', 
                'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA', 'KIRIBATI', 'KOREA, SOUTH', 'KOSOVO', 'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LEBANON', 'LESOTHO', 
                'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MACAU', 'MACEDONIA', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES', 'MALI', 'MALTA', 
                'MEXICO', 'MICRONESIA', 'MOLDOVA', 'MONACO', 'MONGOLIA', 'MONTENEGRO', 
                'MOROCCO', 'MOZAMBIQUE', 'NAMIBIA', 'NAURU', 'NEPAL', 'NETHERLANDS', 'NEW CALEDONIA', 'NEW ZEALAND', 'NICARAGUA', 'NIGER', 'NIGERIA',   
                'NORWAY', 'OMAN', 'PAKISTAN', 'PALAU', 'PANAMA',  'PARAGUAY', 'PERU', 'PHILIPPINES',  'POLAND', 'PORTUGAL', 
                'QATAR', 'REUNION', 'ROMANIA', 'RUSSIA', 'RWANDA', 'SAMOA', 'SAN MARINO', 'SAUDI ARABIA', 'SENEGAL', 'SERBIA', 'SEYCHELLES', 
                'SIERRA LEONE', 'SINGAPORE', 'SINT MAARTEN', 'SLOVAKIA', 'SLOVENIA', 'SOMALIA', 'SOUTH AFRICA', 'SOUTH SUDAN', 'SPAIN', 'SRI LANKA',
                'SUDAN', 'SURINAME', 'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAIWAN', 'TAJIKISTAN', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE',
                'TOGO',  'TONGA',  'TUNISIA', 'TURKEY', 'TURKMENISTAN',  'UGANDA', 
                'UKRAINE', 'UNITED KINGDOM', 'URUGUAY', 'UZBEKISTAN',  'VENEZUELA', 'VIETNAM', 
                'YEMEN', 'ZAMBIA', 'ZIMBABWE']


def get_data_trade(country, exports:bool):

    if exports==True:
        value="ALL_VAL_MO"
    elif exports==False:
        value="GEN_VAL_MO"
    
    data = json.loads((get_data_census("2024", None, exports, 
                        country, None)))
    
    df = pd.DataFrame(data["body"][1:], columns = data["body"][0])
    #print(df)
    df[value] = df[value].astype(float)

    df_anual = df.groupby(["NAICS_LDESC", "CTY_NAME", "NAICS"], as_index=False)[value].sum()
    df_filtrado = df_anual[df_anual["NAICS"].astype(str).str.len() == 2]
    dict_records = df_filtrado.to_dict("records")

    dict_final={}
    for element in dict_records:
        dict_temporal={}
        dict_temporal["NAICS_LDESC"]=element["NAICS_LDESC"]
        dict_temporal[value]=element[value]
        dict_final[element["NAICS"]]=dict_temporal

    return dict_final

def  get_trade_of_country(country: str):
    dict_exports=get_data_trade(country, True)
    dict_imports=get_data_trade(country, False)

    lst_NAICS=set()
    for key in dict_exports.keys():
        lst_NAICS.add(key)
        for key in dict_imports.keys():
            lst_NAICS.add(key)

    dict_final={}
    for NAIC in lst_NAICS:
        #print(NAIC)
        if not NAIC.startswith("9"):
            dict_temporal={}
            if NAIC in dict_imports:
                #print(dict_imports)
                dict_temporal["imports"]=dict_imports[NAIC]["GEN_VAL_MO"]
                dict_temporal["desciption"]=dict_imports[NAIC]["NAICS_LDESC"]
            else:
                #print("We came from here")
                dict_temporal["imports"]=0

            if NAIC in dict_exports:
                
                dict_temporal["exports"]=dict_exports[NAIC]["ALL_VAL_MO"]
                dict_temporal["desciption"]=dict_exports[NAIC]["NAICS_LDESC"]
            else:
                dict_temporal["exports"]=0

            dict_final[NAIC]=dict_temporal
        else:
            pass

    #dict_country={}
    #dict_country[country]=dict_final

    return dict_final



#data_mexico=get_trade_of_country("MEXICO")
'''''''''
paises=['SENEGAL', 'GUINEA', 'SIERRA LEONE', "COTE D'IVOIRE", 'GHANA', 'NIGER', 'TOGO', 'NIGERIA', 'CENTRAL AFRICAN REPUBLIC', 'GABON', 'ST HELENA', 'ANGOLA', 'ETHIOPIA', 'UGANDA', 'KENYA', 'SEYCHELLES', 'TANZANIA', 'MAURITIUS', 'MADAGASCAR', 'COMOROS', 'SOUTH AFRICA', 'ESWATINI', 'MALAWI', 'CANADA', 'MEXICO', 'GUATEMALA', 'EL SALVADOR', 'HONDURAS', 'NICARAGUA', 'COSTA RICA', 'PANAMA', 'JAMAICA', 'HAITI', 'DOMINICAN REPUBLIC', 'TRINIDAD AND TOBAGO', 'COLOMBIA', 'VENEZUELA', 'ECUADOR', 'PERU', 'BOLIVIA', 'CHILE', 'BRAZIL', 'PARAGUAY', 'URUGUAY', 'ARGENTINA', 'ICELAND', 'SWEDEN', 'NORWAY', 'FINLAND', 'DENMARK', 'UNITED KINGDOM', 'IRELAND', 'NETHERLANDS', 'BELGIUM', 'MONACO', 'FRANCE', 'GERMANY', 'AUSTRIA', 'CZECH REPUBLIC', 'SLOVAKIA', 'HUNGARY', 'LIECHTENSTEIN', 'SWITZERLAND', 'ESTONIA', 'LATVIA', 'LITHUANIA', 'POLAND', 'RUSSIA', 'UKRAINE', 'ARMENIA', 'KAZAKHSTAN', 'MOLDOVA', 'TURKMENISTAN', 'UZBEKISTAN', 'SPAIN', 'PORTUGAL', 'MALTA', 'ITALY', 'CROATIA', 'SLOVENIA', 'BOSNIA AND HERZEGOVINA', 'MACEDONIA', 'SERBIA', 'GREECE', 'ROMANIA', 'BULGARIA', 'TURKEY', 'CYPRUS', 'LEBANON', 'IRAQ', 'ISRAEL', 'JORDAN', 'KUWAIT', 'SAUDI ARABIA', 'QATAR', 'UNITED ARAB EMIRATES', 'OMAN', 'INDIA', 'PAKISTAN', 'BANGLADESH', 'SRI LANKA', 'BURMA', 'THAILAND', 'VIETNAM', 'LAOS', 'INDONESIA', 'CAMBODIA', 'MALAYSIA', 'SINGAPORE', 'BRUNEI', 'PHILIPPINES', 'MACAU', 'CHINA', 'KOREA, SOUTH', 'HONG KONG', 'TAIWAN', 'JAPAN', 'AUSTRALIA', 'COCOS (KEELING) ISLANDS', 'NEW ZEALAND', 'MOROCCO', 'ALGERIA', 'TUNISIA', 'LIBYA', 'EGYPT', 'CAMEROON', 'BAHAMAS', 'ST KITTS AND NEVIS', 'LUXEMBOURG', 'FRENCH POLYNESIA', 'BELARUS', 'BAHRAIN', 'GUYANA', 'GEORGIA', 'ALBANIA', 'NEPAL', 'VANUATU', 'FIJI', 'TONGA', 'MAURITANIA', 'ARUBA', 'SAN MARINO', 'SVALBARD, JAN MAYEN ISLAND', 'AFGHANISTAN', 'BELIZE', 'ANGUILLA', 'GRENADA', 'MARTINIQUE', 'ANDORRA', 'AZERBAIJAN', 'KOSOVO', 'YEMEN', 'TIMOR-LESTE', 'PAPUA NEW GUINEA', 'SAMOA', 'SOLOMON ISLANDS', 'MICRONESIA', 'NAURU', 'MAYOTTE', 'CAYMAN ISLANDS', 'SYRIA', 'NIUE', 'MOZAMBIQUE', 'NAMIBIA', 'BOTSWANA', 'ZIMBABWE', 'GREENLAND', 'BERMUDA', 'TURKS AND CAICOS ISLANDS', 'BRITISH VIRGIN ISLANDS', 'ANTIGUA AND BARBUDA', 'MONTSERRAT', 'DOMINICA', 'ST LUCIA', 'ST VINCENT AND THE GRENADINES', 'BARBADOS', 'SINT MAARTEN', 'CURACAO', 'GUADELOUPE', 'SURINAME', 'FAROE ISLANDS', 'KYRGYZSTAN', 'TAJIKISTAN', 'MONTENEGRO', 'MALDIVES', 'MONGOLIA', 'CHRISTMAS ISLAND', 'KIRIBATI', 'TUVALU', 'NEW CALEDONIA', 'MARSHALL ISLANDS', 'MALI', 'BURKINA FASO', 'BENIN', 'CONGO (BRAZZAVILLE)', 'GUINEA-BISSAU', 'CABO VERDE', 'SAO TOME AND PRINCIPE', 'LIBERIA', 'CONGO (KINSHASA)', 'RWANDA', 'SOMALIA', 'DJIBOUTI', 'REUNION', 'ZAMBIA', 'LESOTHO', 'CUBA', 'IRAN', 'BHUTAN', 'COOK ISLANDS', 'ST PIERRE AND MIQUELON', 'FRENCH GUIANA', 'FALKLAND ISLANDS (ISLAS MALVINAS)', 'GIBRALTAR', 'VATICAN CITY', 'WEST BANK ADMINISTERED BY ISRAEL', 'NORFOLK ISLAND', 'TOKELAU', 'PITCAIRN ISLANDS', 'PALAU', 'SUDAN', 'SOUTH SUDAN', 'EQUATORIAL GUINEA', 'GAMBIA', 'CHAD', 'BURUNDI', 'ERITREA', 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANDORRA', 'ANGOLA', 'ANGUILLA', 'ANTIGUA AND BARBUDA', 'ARGENTINA', 'ARMENIA', 'ARUBA', 'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUS', 'BELGIUM', 'BELIZE', 'BENIN', 'BERMUDA', 'BHUTAN', 'BOLIVIA', 'BOSNIA AND HERZEGOVINA', 'BOTSWANA', 'BRAZIL', 'BRITISH VIRGIN ISLANDS', 'BRUNEI', 'BULGARIA', 'BURKINA FASO', 'BURMA', 'BURUNDI', 'CABO VERDE', 'CAMBODIA', 'CAMEROON', 'CANADA', 'CAYMAN ISLANDS', 'CENTRAL AFRICAN REPUBLIC', 'CHAD', 'CHILE', 'CHINA', 'CHRISTMAS ISLAND', 'COCOS (KEELING) ISLANDS', 'COLOMBIA', 'COMOROS', 'CONGO (BRAZZAVILLE)', 'CONGO (KINSHASA)', 'COOK ISLANDS', 'COSTA RICA', "COTE D'IVOIRE", 'CROATIA', 'CUBA', 'CURACAO', 'CYPRUS', 'CZECH REPUBLIC', 'DENMARK', 'DJIBOUTI', 'DOMINICA', 'DOMINICAN REPUBLIC', 'ECUADOR', 'EGYPT', 'EL SALVADOR', 'EQUATORIAL GUINEA', 'ERITREA', 'ESTONIA', 'ESWATINI', 'ETHIOPIA', 'FALKLAND ISLANDS (ISLAS MALVINAS)', 'FAROE ISLANDS', 'FIJI', 'FINLAND', 'FRANCE', 'FRENCH GUIANA', 'FRENCH POLYNESIA', 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'GABON', 'GAMBIA', 'GEORGIA', 'GERMANY', 'GHANA', 'GIBRALTAR', 'GREECE', 'GREENLAND', 'GRENADA', 'GUADELOUPE', 'GUATEMALA', 'GUINEA', 'GUINEA-BISSAU', 'GUYANA', 'HAITI', 'HONDURAS', 'HONG KONG', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'IRELAND', 'ISRAEL', 'ITALY', 'JAMAICA', 'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA', 'KIRIBATI', 'KOREA, SOUTH', 'KOSOVO', 'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LEBANON', 'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MACAU', 'MACEDONIA', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES', 'MALI', 'MALTA', 'MARSHALL ISLANDS', 'MARTINIQUE', 'MAURITANIA', 'MAURITIUS', 'MAYOTTE', 'MEXICO', 'MICRONESIA', 'MOLDOVA', 'MONACO', 'MONGOLIA', 'MONTENEGRO', 'MONTSERRAT', 'MOROCCO', 'MOZAMBIQUE', 'NAMIBIA', 'NAURU', 'NEPAL', 'NETHERLANDS', 'NEW CALEDONIA', 'NEW ZEALAND', 'NICARAGUA', 'NIGER', 'NIGERIA', 'NIUE', 'NORFOLK ISLAND', 'NORWAY', 'OMAN', 'PAKISTAN', 'PALAU', 'PANAMA', 'PAPUA NEW GUINEA', 'PARAGUAY', 'PERU', 'PHILIPPINES', 'PITCAIRN ISLANDS', 'POLAND', 'PORTUGAL', 'QATAR', 'REUNION', 'ROMANIA', 'RUSSIA', 'RWANDA', 'SAMOA', 'SAN MARINO', 'SAO TOME AND PRINCIPE', 'SAUDI ARABIA', 'SENEGAL', 'SERBIA', 'SEYCHELLES', 'SIERRA LEONE', 'SINGAPORE', 'SINT MAARTEN', 'SLOVAKIA', 'SLOVENIA', 'SOLOMON ISLANDS', 'SOMALIA', 'SOUTH AFRICA', 'SOUTH SUDAN', 'SPAIN', 'SRI LANKA', 'ST HELENA', 'ST KITTS AND NEVIS', 'ST LUCIA', 'ST PIERRE AND MIQUELON', 'ST VINCENT AND THE GRENADINES', 'SUDAN', 'SURINAME', 'SVALBARD, JAN MAYEN ISLAND', 'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAIWAN', 'TAJIKISTAN', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE', 'TOGO', 'TOKELAU', 'TONGA', 'TRINIDAD AND TOBAGO', 'TUNISIA', 'TURKEY', 'TURKMENISTAN', 'TURKS AND CAICOS ISLANDS', 'TUVALU', 'UGANDA', 'UKRAINE', 'UNITED ARAB EMIRATES', 'UNITED KINGDOM', 'URUGUAY', 'UZBEKISTAN', 'VANUATU', 'VATICAN CITY', 'VENEZUELA', 'VIETNAM', 'WEST BANK ADMINISTERED BY ISRAEL', 'YEMEN', 'ZAMBIA','ZIMBABWE']
paises_unicos=set()
for pais in paises:
    paises_unicos.add(pais)

dict_count={}
for pais in paises_unicos:
    dict_count[pais]=0

for pais in paises:
    dict_count[pais]=dict_count[pais]+1

lst_countries=[]

for key, value in dict_count.items():
    if value==2:
        lst_countries.append(key)

print(lst_countries)
'''''''''


#lst_countries=['MAYOTTE', 'PAPUA NEW GUINEA', 'PERU', 'VENEZUELA', 'VIETNAM', 'MALTA', 'COOK ISLANDS', 'PARAGUAY', 'QATAR', 'BURMA', 'IRAN', 'AUSTRALIA', 'TAIWAN', 'BELGIUM', 'SUDAN', 'BANGLADESH', 'CENTRAL AFRICAN REPUBLIC', 'SOLOMON ISLANDS', 'TOGO', 'DJIBOUTI', 'CHILE', 'MOZAMBIQUE', 'KENYA', 'NORWAY', 'SWEDEN', 'WEST BANK ADMINISTERED BY ISRAEL', 'NIUE', 'SVALBARD, JAN MAYEN ISLAND', 'BOSNIA AND HERZEGOVINA', 'FIJI', 'FALKLAND ISLANDS (ISLAS MALVINAS)', 'KIRIBATI', 'MAURITIUS', 'ANGUILLA', 'ST VINCENT AND THE GRENADINES', 'MAURITANIA', 'TUVALU', 'ZAMBIA', 'CHINA', 'NEW ZEALAND', 'KOSOVO', 'HONG KONG', 'NICARAGUA', 'TRINIDAD AND TOBAGO', 'ZIMBABWE', 'GUADELOUPE', 'GUINEA-BISSAU', 'GEORGIA', 'KOREA, SOUTH', 'BERMUDA', 'SINT MAARTEN', 'BULGARIA', 'MALI', 'DOMINICA', 'VATICAN CITY', 'CROATIA', 'SAO TOME AND PRINCIPE', 'SURINAME', 'SWITZERLAND', 'CABO VERDE', 'LEBANON', 'SAMOA', 'BARBADOS', 'MACEDONIA', 'LIBYA', 'ARUBA', 'NIGER', 'VANUATU', 'COMOROS', 'MONGOLIA', 'ALGERIA', 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'MICRONESIA', 'AZERBAIJAN', 'ANTIGUA AND BARBUDA', 'CAMEROON', 'BRUNEI', 'AUSTRIA', 'ROMANIA', "COTE D'IVOIRE", 'IRAQ', 'ITALY', 'PAKISTAN', 'KAZAKHSTAN', 'COCOS (KEELING) ISLANDS', 'JAMAICA', 'MARTINIQUE', 'SIERRA LEONE', 'PITCAIRN ISLANDS', 'GAMBIA', 'TURKS AND CAICOS ISLANDS', 'HUNGARY', 'ALBANIA', 'LESOTHO', 'ST LUCIA', 'MADAGASCAR', 'ETHIOPIA', 'UNITED ARAB EMIRATES', 'CHRISTMAS ISLAND', 'INDIA', 'ERITREA', 'LAOS', 'NIGERIA', 'TOKELAU', 'GUYANA', 'SOUTH AFRICA', 'ESWATINI', 'OMAN', 'UKRAINE', 'ISRAEL', 'MALAWI', 'MARSHALL ISLANDS', 'SPAIN', 'RUSSIA', 'AFGHANISTAN', 'ST PIERRE AND MIQUELON', 'BURKINA FASO', 'SOUTH SUDAN', 'NEW CALEDONIA', 'CAYMAN ISLANDS', 'URUGUAY', 'EGYPT', 'INDONESIA', 'GHANA', 'NORFOLK ISLAND', 'SEYCHELLES', 'ST KITTS AND NEVIS', 'TIMOR-LESTE', 'TUNISIA', 'COLOMBIA', 'NETHERLANDS', 'ECUADOR', 'FRENCH GUIANA', 'EL SALVADOR', 'LUXEMBOURG', 'TURKEY', 'MONTENEGRO', 'SINGAPORE', 'KYRGYZSTAN', 'LIECHTENSTEIN', 'UZBEKISTAN', 'IRELAND', 'CANADA', 'BOTSWANA', 'TONGA', 'UNITED KINGDOM', 'LATVIA', 'LITHUANIA', 'LIBERIA', 'PHILIPPINES', 'BELIZE', 'JORDAN', 'PORTUGAL', 'BHUTAN', 'TANZANIA', 'ANGOLA', 'BAHAMAS', 'REUNION', 'GIBRALTAR', 'PALAU', 'GUINEA', 'PANAMA', 'CZECH REPUBLIC', 'JAPAN', 'FRANCE', 'ANDORRA', 'SAN MARINO', 'CYPRUS', 'COSTA RICA', 'GREENLAND', 'TAJIKISTAN', 'SRI LANKA', 'NEPAL', 'SYRIA', 'MALAYSIA', 'MONTSERRAT', 'KUWAIT', 'BENIN', 'SENEGAL', 'DENMARK', 'BRITISH VIRGIN ISLANDS', 'MEXICO', 'MACAU', 'SERBIA', 'UGANDA', 'CONGO (KINSHASA)', 'THAILAND', 'CUBA', 'SOMALIA', 'CAMBODIA', 'CURACAO', 'MONACO', 'FAROE ISLANDS', 'ST HELENA', 'GUATEMALA', 'ICELAND', 'MALDIVES', 'GREECE', 'BRAZIL', 'POLAND', 'SLOVAKIA', 'BOLIVIA', 'NAURU', 'RWANDA', 'SAUDI ARABIA', 'ESTONIA', 'SLOVENIA', 'CHAD', 'CONGO (BRAZZAVILLE)', 'HONDURAS', 'YEMEN', 'MOLDOVA', 'EQUATORIAL GUINEA', 'ARGENTINA', 'FINLAND', 'FRENCH POLYNESIA', 'DOMINICAN REPUBLIC', 'MOROCCO', 'BELARUS', 'GRENADA', 'BAHRAIN', 'ARMENIA', 'NAMIBIA', 'TURKMENISTAN', 'HAITI', 'BURUNDI', 'GERMANY', 'GABON']
#lst_countries=['AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANDORRA', 'ANGOLA', 'ANGUILLA', 'ANTIGUA AND BARBUDA', 'ARGENTINA', 'ARMENIA', 'ARUBA', 'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUS', 'BELGIUM', 'BELIZE', 'BENIN', 'BERMUDA', 'BHUTAN', 'BOLIVIA', 'BOSNIA AND HERZEGOVINA', 'BOTSWANA', 'BRAZIL', 'BRITISH VIRGIN ISLANDS', 'BRUNEI', 'BULGARIA', 'BURKINA FASO', 'BURMA', 'BURUNDI', 'CABO VERDE', 'CAMBODIA', 'CAMEROON', 'CANADA', 'CAYMAN ISLANDS', 'CENTRAL AFRICAN REPUBLIC', 'CHAD', 'CHILE', 'CHINA', 'CHRISTMAS ISLAND', 'COCOS (KEELING) ISLANDS', 'COLOMBIA', 'COMOROS', 'CONGO (BRAZZAVILLE)', 'CONGO (KINSHASA)', 'COOK ISLANDS', 'COSTA RICA', "COTE D'IVOIRE", 'CROATIA', 'CUBA', 'CURACAO', 'CYPRUS', 'CZECH REPUBLIC', 'DENMARK', 'DJIBOUTI', 'DOMINICA', 'DOMINICAN REPUBLIC', 'ECUADOR', 'EGYPT', 'EL SALVADOR', 'EQUATORIAL GUINEA', 'ERITREA', 'ESTONIA', 'ESWATINI', 'ETHIOPIA', 'FALKLAND ISLANDS (ISLAS MALVINAS)', 'FAROE ISLANDS', 'FIJI', 'FINLAND', 'FRANCE', 'FRENCH GUIANA', 'FRENCH POLYNESIA', 'FRENCH SOUTHERN AND ANTARCTIC LANDS', 'GABON', 'GAMBIA', 'GEORGIA', 'GERMANY', 'GHANA', 'GIBRALTAR', 'GREECE', 'GREENLAND', 'GRENADA', 'GUADELOUPE', 'GUATEMALA', 'GUINEA', 'GUINEA-BISSAU', 'GUYANA', 'HAITI', 'HONDURAS', 'HONG KONG', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAN', 'IRAQ', 'IRELAND', 'ISRAEL', 'ITALY', 'JAMAICA', 'JAPAN', 'JORDAN', 'KAZAKHSTAN', 'KENYA', 'KIRIBATI', 'KOREA, SOUTH', 'KOSOVO', 'KUWAIT', 'KYRGYZSTAN', 'LAOS', 'LATVIA', 'LEBANON', 'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MACAU', 'MACEDONIA', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES', 'MALI', 'MALTA', 'MARSHALL ISLANDS', 'MARTINIQUE', 'MAURITANIA', 'MAURITIUS', 'MAYOTTE', 'MEXICO', 'MICRONESIA', 'MOLDOVA', 'MONACO', 'MONGOLIA', 'MONTENEGRO', 'MONTSERRAT', 'MOROCCO', 'MOZAMBIQUE', 'NAMIBIA', 'NAURU', 'NEPAL', 'NETHERLANDS', 'NEW CALEDONIA', 'NEW ZEALAND', 'NICARAGUA', 'NIGER', 'NIGERIA', 'NIUE', 'NORFOLK ISLAND', 'NORWAY', 'OMAN', 'PAKISTAN', 'PALAU', 'PANAMA', 'PAPUA NEW GUINEA', 'PARAGUAY', 'PERU', 'PHILIPPINES', 'PITCAIRN ISLANDS', 'POLAND', 'PORTUGAL', 'QATAR', 'REUNION', 'ROMANIA', 'RUSSIA', 'RWANDA', 'SAMOA', 'SAN MARINO', 'SAO TOME AND PRINCIPE', 'SAUDI ARABIA', 'SENEGAL', 'SERBIA', 'SEYCHELLES', 'SIERRA LEONE', 'SINGAPORE', 'SINT MAARTEN', 'SLOVAKIA', 'SLOVENIA', 'SOLOMON ISLANDS', 'SOMALIA', 'SOUTH AFRICA', 'SOUTH SUDAN', 'SPAIN', 'SRI LANKA', 'ST HELENA', 'ST KITTS AND NEVIS', 'ST LUCIA', 'ST PIERRE AND MIQUELON', 'ST VINCENT AND THE GRENADINES', 'SUDAN', 'SURINAME', 'SVALBARD, JAN MAYEN ISLAND', 'SWEDEN', 'SWITZERLAND', 'SYRIA', 'TAIWAN', 'TAJIKISTAN', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE', 'TOGO', 'TOKELAU', 'TONGA', 'TRINIDAD AND TOBAGO', 'TUNISIA', 'TURKEY', 'TURKMENISTAN', 'TURKS AND CAICOS ISLANDS', 'TUVALU', 'UGANDA', 'UKRAINE', 'UNITED ARAB EMIRATES', 'UNITED KINGDOM', 'URUGUAY', 'UZBEKISTAN', 'VANUATU', 'VATICAN CITY', 'VENEZUELA', 'VIETNAM', 'WEST BANK ADMINISTERED BY ISRAEL', 'YEMEN', 'ZAMBIA', 'ZIMBABWE']


#eliminated: Antigua and barbuda, 'BOSNIA AND HERZEGOVINA''BRITISH VIRGIN ISLANDS','CENTRAL AFRICAN REPUBLIC','CHRISTMAS ISLAND', 'COCOS (KEELING) ISLANDS''NORFOLK ISLAND',
#'CONGO (BRAZZAVILLE)' 'CONGO (KINSHASA)', 'COOK ISLANDS',  'FALKLAND ISLANDS (ISLAS MALVINAS)','MONTSERRAT',  'ST HELENA', 'ST KITTS AND NEVIS', 'ST LUCIA', 'ST PIERRE AND MIQUELON', 'ST VINCENT AND THE GRENADINES',
# 'WEST BANK ADMINISTERED BY ISRAEL','MARSHALL ISLANDS', 'MARTINIQUE', 'MAURITANIA', 'MAURITIUS', 'MAYOTTE','NIUE',, 'ERITREA', 'PAPUA NEW GUINEA','PITCAIRN ISLANDS','SAO TOME AND PRINCIPE', 
#'FRENCH GUIANA', 'FRENCH POLYNESIA', 'FRENCH SOUTHERN AND ANTARCTIC LANDS','FIJI', 'EQUATORIAL GUINEA' 'TUVALU' 'SOLOMON ISLANDS' 'SVALBARD, JAN MAYEN ISLAND','TOKELAU','VANUATU'
#'TRINIDAD AND TOBAGO',, 'TURKS AND CAICOS ISLANDS'
#### "COTE D'IVOIRE"  'DOMINICAN REPUBLIC' , 'UNITED ARAB EMIRATES
#lst_countries.sort()
#print(lst_countries)
#trade_country=get_trade_of_country("PERU")
#print(trade_country)

dict_final_countries={}
for country in COUNTRIES:
    #print(country)
    trade_country=get_trade_of_country(country)
    dict_final_countries[country]=trade_country


#print(dict_final_countries)
EXPORTS_JSON = Path(__file__).parent / "data/exports.json"  

with open(EXPORTS_JSON, "w", encoding="utf-8") as file:
    json.dump(dict_final_countries, file, indent=4, ensure_ascii=False)
